### Создаем продавца
POST http://localhost:8000/api/v1/seller/ HTTP/1.1
Content-Type: application/json

{
    "first_name": "Ivan",
    "last_name": "Ivanov",
    "e_mail": "ivanov@example.com",
    "password": "secret123"
}

### Получаем список продавцов (без паролей)
GET http://localhost:8000/api/v1/seller/ HTTP/1.1

### Получаем данные конкретного продавца (и список его книг)
GET http://localhost:8000/api/v1/seller/1 HTTP/1.1

### Обновляем данные продавца (без пароля)
PUT http://localhost:8000/api/v1/seller/1 HTTP/1.1
Content-Type: application/json

{
    "first_name": "Ivan",
    "last_name": "Petrov",
    "e_mail": "ivan.petrov@example.com"
}

### Создаем книгу, привязываем к продавцу с id=1
POST http://localhost:8000/api/v1/books/ HTTP/1.1
Content-Type: application/json

{
    "title": "Clean Architecture",
    "author": "Robert Martin",
    "count_pages": 300,
    "year": 2025,
    "seller_id": 1
}

### Получаем список книг
GET http://localhost:8000/api/v1/books/ HTTP/1.1

### Получаем одну книгу по ее ИД
GET http://localhost:8000/api/v1/books/1 HTTP/1.1

### Обновляем поля в данных о книге
PUT http://localhost:8000/api/v1/books/1 HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "title": "Clean Code",
    "author": "Robert Martin",
    "year": 2022,
    "pages": 310,
    "seller_id": 1
}

### Удаляем книгу
DELETE http://localhost:8000/api/v1/books/1 HTTP/1.1

### Удаляем продавца (вместе с его книгами)
DELETE http://localhost:8000/api/v1/seller/1 HTTP/1.1
